# Generated by Django 4.2.1 on 2023-05-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='country',
        ),
        migrations.AddField(
            model_name='myuser',
            name='Gender',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phonenumber',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
